### ISSUE TITLE
s_axilite ports should not be used for array arguments

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/dahlia#251]
According to [Vivado HLS documentation](https://gist.github.com/rachitnigam/188cb4edbf734e6785b3e90eb7c5da0a#interfaces), `s_axilite` interfaces should be generated for non-array arguments.

The wording in the [INTERFACE pragma](https://www.xilinx.com/html_docs/xilinx2017_4/sdaccel_doc/jit1504034365862.html) also implies that it generates a register map. (See under `offset`)

Weirdly, under [Creating SDAccel kernels](https://www.xilinx.com/html_docs/xilinx2019_1/sdaccel_doc/kqq1541628561426.html#kqq1541628561426), array arguments are mapped with both `m_axi` and `s_axilite` interfaces.

**Comment by rachitnigam** [comment]
@ViviYe pointed out [this example](https://www.xilinx.com/html_docs/xilinx2017_4/sdaccel_doc/jka1504034359550.html) from the SDAccel repo which claims that arrays in fact require both `m_axi` and `s_axilite`.

**Comment by sampsyo** [comment]
That's quite contradictory! It clearly says:

> The AXI4 interfaces supported by Vivado HLS include the AXI4-Stream (axis), AXI4-Lite (s_axilite), and AXI4 master (m_axi) interfaces, which you can specify as follows:
> [...]
> AXI4-Lite interface: Specify on any type of argument except arrays.

**Comment by rachitnigam** [comment]
[This job](http://ec2-54-234-195-6.compute-1.amazonaws.com:5000/jobs/IToLeLnS7Yc.html) provides some insight in SDAccel's implicit checks for interfaces:


**ERROR**: [XOCC 213-400] The Vivado HLS generated IP does not comply with SDAccel integration requirements. Check interface pragmas to ensure the design only uses one s_axilite interface including the 'return' port and one or more m_axi interfaces with offset=slave set to the s_axilite interface; there should not be any other port interface used.
