### ISSUE TITLE
hls ignores our wishes

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/dahlia#289]
``` 
15 WARNING: [BIND 205-102] The specified resource core for memory 'orig_0_3' will be ignored if a simpler one can be used.
```
even when an explicit resource pragma is given, HLS might ignore it

**Comment by rachitnigam** [comment]
Similar argument to https://github.com/cucapra/dahlia/issues/275#issuecomment-583701129.

**Comment by rachitnigam** [comment]
Sometimes, life gives lemons. Well, life asks HLS to give an applie and but instead it gives you a lemon.

**Comment by rachitnigam** [comment]
I don't know if this issue is particularly actionable (or ever was). Closing it and hoping for a brighter, open-source future where we can control the generated memories.
